# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fluency_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import recognition_config_pb2 as recognition__config__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66luency_service.proto\x12\rbaikal.speech\x1a\x18recognition_config.proto\x1a\x1cgoogle/protobuf/struct.proto\"S\n\x0ePredictRequest\x12\x0c\n\x04wave\x18\x01 \x01(\x0c\x12\x0c\n\x04text\x18\x02 \x01(\t\x12%\n\x06\x65ngine\x18\x03 \x01(\x0e\x32\x15.baikal.speech.Engine\":\n\x0fPredictResponse\x12\'\n\x06result\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2\\\n\x0e\x46luencyService\x12J\n\x07Predict\x12\x1d.baikal.speech.PredictRequest\x1a\x1e.baikal.speech.PredictResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fluency_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PREDICTREQUEST']._serialized_start=96
  _globals['_PREDICTREQUEST']._serialized_end=179
  _globals['_PREDICTRESPONSE']._serialized_start=181
  _globals['_PREDICTRESPONSE']._serialized_end=239
  _globals['_FLUENCYSERVICE']._serialized_start=241
  _globals['_FLUENCYSERVICE']._serialized_end=333
# @@protoc_insertion_point(module_scope)
