# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recognition_config.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18recognition_config.proto\x12\rbaikal.speech\"\x9a\x02\n\x11RecognitionConfig\x12.\n\x08\x65ncoding\x18\x01 \x01(\x0e\x32\x1c.baikal.speech.AudioEncoding\x12\x13\n\x0bsample_rate\x18\x02 \x01(\x05\x12\x15\n\rchannel_count\x18\x03 \x01(\x05\x12\x19\n\x11\x65nable_confidence\x18\x04 \x01(\x08\x12 \n\x18\x65nable_word_time_offsets\x18\x05 \x01(\x08\x12 \n\x18\x65nable_char_time_offsets\x18\x06 \x01(\x08\x12#\n\x1b\x65nable_phoneme_time_offsets\x18\x07 \x01(\x08\x12%\n\x06\x65ngine\x18\x08 \x01(\x0e\x32\x15.baikal.speech.Engine*3\n\rAudioEncoding\x12\x14\n\x10UNKNOWN_ENCODING\x10\x00\x12\x0c\n\x08LINEAR16\x10\x01*8\n\x06\x45ngine\x12\x12\n\x0eUNKNOWN_ENGINE\x10\x00\x12\x0b\n\x07WHISPER\x10\x01\x12\r\n\tBaikalSTT\x10\x02\x42\x39\x42\x16RecognitionConfigProtoP\x01Z\x1d\x62\x61ikal.ai/proto/baikal/speechb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recognition_config_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\026RecognitionConfigProtoP\001Z\035baikal.ai/proto/baikal/speech'
  _globals['_AUDIOENCODING']._serialized_start=328
  _globals['_AUDIOENCODING']._serialized_end=379
  _globals['_ENGINE']._serialized_start=381
  _globals['_ENGINE']._serialized_end=437
  _globals['_RECOGNITIONCONFIG']._serialized_start=44
  _globals['_RECOGNITIONCONFIG']._serialized_end=326
# @@protoc_insertion_point(module_scope)
